In [1]:
import numpy as np 
import pandas as pd

In [2]:
df = pd.read_csv("500_Person_Gender_Height_Weight_Index.csv")
df

Gender  Height  Weight  Index
0      Male     174      96      4
1      Male     189      87      2
2    Female     185     110      4
3    Female     195     104      3
4      Male     149      61      3
..      ...     ...     ...    ...
495  Female     150     153      5
496  Female     184     121      4
497  Female     141     136      5
498    Male     150      95      5
499    Male     173     131      5

[500 rows x 4 columns]

In [3]:
df.head()

Gender  Height  Weight  Index
0    Male     174      96      4
1    Male     189      87      2
2  Female     185     110      4
3  Female     195     104      3
4    Male     149      61      3

In [4]:
df.tail()

Gender  Height  Weight  Index
495  Female     150     153      5
496  Female     184     121      4
497  Female     141     136      5
498    Male     150      95      5
499    Male     173     131      5

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Gender  500 non-null    object
 1   Height  500 non-null    int64 
 2   Weight  500 non-null    int64 
 3   Index   500 non-null    int64 
dtypes: int64(3), object(1)
memory usage: 15.8+ KB


In [6]:
data = df.iloc[:, 1:].values
data

array([[174,  96,   4],
       [189,  87,   2],
       [185, 110,   4],
       ...,
       [141, 136,   5],
       [150,  95,   5],
       [173, 131,   5]])

##### Question 1 : Find the number of dimensions , the size and the shape of this array

In [7]:
print("The number of dimensions : ", np.ndim(data))
print("The size of this array : ", np.array(data).size)
print("The shape of this array : ", np.array(data).shape)

The number of dimensions :  2
The size of this array :  1500
The shape of this array :  (500, 3)


##### Question 2 : What is the data type of this array ?

In [8]:
Type = data.dtype
print("The data type of this array : ", Type)

The data type of this array :  int64


##### Question 3 : Return the target value of the 500 Observation 

In [9]:
Target = data[:,2]
Target

array([4, 2, 4, 3, 3, 3, 5, 5, 3, 4, 2, 4, 3, 2, 2, 5, 5, 5, 5, 5, 5, 5,
       4, 5, 2, 3, 3, 1, 5, 5, 5, 1, 1, 5, 5, 4, 3, 4, 5, 2, 4, 5, 2, 5,
       4, 2, 4, 4, 3, 5, 5, 1, 5, 4, 4, 3, 4, 5, 3, 5, 0, 5, 0, 2, 5, 5,
       4, 2, 4, 4, 2, 4, 5, 2, 3, 4, 4, 4, 4, 0, 3, 5, 3, 4, 5, 0, 5, 5,
       5, 5, 5, 3, 3, 2, 4, 5, 4, 5, 1, 0, 4, 5, 5, 4, 4, 4, 5, 5, 4, 3,
       4, 5, 4, 2, 4, 3, 2, 5, 5, 5, 4, 4, 4, 5, 5, 4, 4, 4, 5, 2, 5, 2,
       5, 4, 5, 5, 5, 3, 5, 5, 2, 4, 5, 5, 5, 4, 3, 5, 3, 3, 0, 3, 3, 5,
       5, 4, 3, 5, 3, 4, 2, 2, 3, 5, 4, 2, 4, 5, 3, 2, 4, 5, 5, 4, 4, 4,
       4, 3, 5, 3, 3, 4, 4, 2, 3, 3, 5, 3, 5, 4, 5, 5, 4, 5, 5, 5, 4, 4,
       5, 5, 1, 3, 4, 4, 5, 4, 5, 4, 3, 4, 4, 5, 5, 5, 0, 5, 5, 5, 5, 5,
       2, 5, 4, 5, 0, 5, 3, 4, 5, 5, 4, 2, 3, 3, 4, 3, 5, 5, 2, 5, 3, 2,
       1, 5, 0, 5, 3, 5, 3, 4, 3, 5, 5, 5, 5, 2, 4, 5, 5, 4, 5, 5, 5, 2,
       4, 5, 5, 5, 5, 1, 5, 5, 4, 0, 3, 3, 4, 2, 3, 1, 1, 5, 5, 4, 4, 4,
       4, 5, 2, 5, 4, 3, 3, 4, 5, 5, 2, 4, 3, 4, 5,

##### 4- Extract every 3 observations of the data


In [10]:
Observations = data[::3,:]
# print("The 3 observation : ", Observations)
Observations

array([[174,  96,   4],
       [195, 104,   3],
       [147,  92,   5],
       [169, 103,   4],
       [192, 101,   3],
       [153, 107,   5],
       [144, 145,   5],
       [153, 149,   5],
       [172,  67,   2],
       [187,  62,   1],
       [153, 121,   5],
       [160, 131,   5],
       [197, 114,   3],
       [185,  81,   2],
       [157,  56,   2],
       [185,  76,   2],
       [161,  72,   3],
       [176,  54,   1],
       [196, 116,   4],
       [178, 127,   5],
       [191,  54,   0],
       [190,  83,   2],
       [172,  96,   4],
       [194, 136,   4],
       [141,  80,   5],
       [197, 154,   4],
       [176, 122,   4],
       [166, 140,   5],
       [168, 123,   5],
       [145, 117,   5],
       [178, 154,   5],
       [177,  61,   2],
       [142,  69,   4],
       [190,  50,   0],
       [161, 155,   5],
       [195, 126,   4],
       [181, 106,   4],
       [146, 157,   5],
       [177,  96,   4],
       [146, 104,   5],
       [168,  87,   4],
       [184, 160

##### 5- Extract the first and last columns in one array. (using hstack)


In [11]:
data

array([[174,  96,   4],
       [189,  87,   2],
       [185, 110,   4],
       ...,
       [141, 136,   5],
       [150,  95,   5],
       [173, 131,   5]])

In [12]:
First_Col = data[:,0]
# First_Col.shape
Last_Col = data[:,2]
# Last_Col.shape
np.hstack((First_Col.reshape(500,1),Last_Col.reshape(500,1)))



array([[174,   4],
       [189,   2],
       [185,   4],
       [195,   3],
       [149,   3],
       [189,   3],
       [147,   5],
       [154,   5],
       [174,   3],
       [169,   4],
       [195,   2],
       [159,   4],
       [192,   3],
       [155,   2],
       [191,   2],
       [153,   5],
       [157,   5],
       [140,   5],
       [144,   5],
       [172,   5],
       [157,   5],
       [153,   5],
       [169,   4],
       [185,   5],
       [172,   2],
       [151,   3],
       [190,   3],
       [187,   1],
       [163,   5],
       [179,   5],
       [153,   5],
       [178,   1],
       [195,   1],
       [160,   5],
       [157,   5],
       [189,   4],
       [197,   3],
       [144,   4],
       [171,   5],
       [185,   2],
       [175,   4],
       [149,   5],
       [157,   2],
       [161,   5],
       [182,   4],
       [185,   2],
       [188,   4],
       [181,   4],
       [161,   3],
       [140,   5],
       [168,   5],
       [176,   1],
       [163,

##### 6- Reverse the array (the last obseravtion becomes the first)


In [13]:
Reverse = data[:,::-1]
Reverse

array([[  4,  96, 174],
       [  2,  87, 189],
       [  4, 110, 185],
       ...,
       [  5, 136, 141],
       [  5,  95, 150],
       [  5, 131, 173]])

##### 7-What is the maximum and minimum height 

In [14]:
data

array([[174,  96,   4],
       [189,  87,   2],
       [185, 110,   4],
       ...,
       [141, 136,   5],
       [150,  95,   5],
       [173, 131,   5]])

In [15]:
Height = data[:,0]
Max_height = np.max(Height)
print("The maximum height is : ", Max_height,"cm")
Min_height = np.min(Height)
print("The Minimum height is : ", Min_height,"cm")

The maximum height is :  199 cm
The Minimum height is :  140 cm


##### 8-What is the maximum and minimum weight 

In [16]:
Weight = data[:,1]
Max_weight = np.max(Weight)
print("The maximum weight is : ", Max_weight,"kg")
Min_weight = np.min(Weight)
print("The minimum weight is : ", Min_weight,"kg")


The maximum weight is :  160 kg
The minimum weight is :  50 kg


##### 9-Find the mean and standard deviation of height using the simple operation only 

In [17]:
data

array([[174,  96,   4],
       [189,  87,   2],
       [185, 110,   4],
       ...,
       [141, 136,   5],
       [150,  95,   5],
       [173, 131,   5]])

In [18]:
Mean_height = Height.sum()/Height.shape[0]

print("The mean of height with simple operation : ", Mean_height)

The mean of height with simple operation :  169.944


In [19]:
squared_differences = (Height - Mean_height) ** 2
variance = np.sum(squared_differences)/Height.shape[0]
std_dev = np.sqrt(variance)
print("Standard Deviation:", std_dev)



Standard Deviation: 16.35887722308594


##### 10-Find the mean and standard deviation of height using the simple operation only 

In [20]:
data

array([[174,  96,   4],
       [189,  87,   2],
       [185, 110,   4],
       ...,
       [141, 136,   5],
       [150,  95,   5],
       [173, 131,   5]])

In [21]:
Mean_weight = Weight.sum()/Weight.shape[0]

print("The mean of height with simple operation : ", Mean_weight)

The mean of height with simple operation :  106.0


In [22]:
squared_differences = (Weight - Mean_weight) ** 2
variance = np.sum(squared_differences)/Weight.shape[0]
std_dev = np.sqrt(variance)
print("Standard Deviation:", std_dev)



Standard Deviation: 32.350208654659404


##### 11- Find the mean and standard deviation of height 

In [23]:
Mean_height1 = np.mean(Height)
print("The mean of height is : ", Mean_height1,"cm")

The mean of height is :  169.944 cm


In [24]:
Std_dev1_height = np.std(Height)
print("The Standard deviation of height is : ", Std_dev1_height)

The Standard deviation of height is :  16.35887722308594


##### 12- Find the mean and standard deviation of weight 

In [25]:
Mean_weight1 = np.mean(Weight)
print("The mean of weight is : ", Mean_weight1 ,"Kg")

The mean of weight is :  106.0 Kg


In [26]:
Std_dev1_weight = np.std(Weight)
print("The standard deviation of weight is : ", Std_dev1_weight)

The standard deviation of weight is :  32.350208654659404


##### 13- Find the 25th, 75th percentile and the median of height 

In [27]:
Percentile_25 = np.percentile(Height, 25)
Percentile_50 = np.percentile(Height, 50)
Percentile_75 = np.percentile(Height, 75)

print("The Percentile 25th  (Q1):", Percentile_25)
print("The median of height (Q2) :", Percentile_50)
print("The Percentile 75th  (Q3):", Percentile_75)

x = np.percentile(Height,[25,50,75])
x


The Percentile 25th  (Q1): 156.0
The median of height (Q2) : 170.5
The Percentile 75th  (Q3): 184.0


array([156. , 170.5, 184. ])

##### 14-Find the 25th, 75th percentile and the median for weight

In [28]:
Percentile_25 = np.percentile(Weight, 25)
Percentile_50 = np.percentile(Weight, 50)
Percentile_75 = np.percentile(Weight, 75)

print("The Percentile 25th  (Q1):", Percentile_25)
print("The median of height (Q2) :", Percentile_50)
print("The Percentile 75th  (Q3):", Percentile_75)

x = np.percentile(Weight,[25,50,75])
x

The Percentile 25th  (Q1): 80.0
The median of height (Q2) : 106.0
The Percentile 75th  (Q3): 136.0


array([ 80., 106., 136.])

##### 15- Normalize height and width 

In [29]:
Normalized_Height = (Height-Mean_height) / Std_dev1_height
print("Normalized data (Min-Max):", Normalized_Height)

Normalized data (Min-Max): [ 0.24793878  1.16487212  0.92035656  1.53164546 -1.28028346  1.16487212
 -1.40254124 -0.97463902  0.24793878 -0.05770567  1.53164546 -0.66899457
  1.34825879 -0.91351013  1.2871299  -1.03576791 -0.79125235 -1.83044347
 -1.58592791  0.125681   -0.79125235 -1.03576791 -0.05770567  0.92035656
  0.125681   -1.15802568  1.22600101  1.04261434 -0.42447901  0.55358322
 -1.03576791  0.49245433  1.53164546 -0.60786568 -0.79125235  1.16487212
  1.65390324 -1.58592791  0.06455211  0.92035656  0.30906767 -1.28028346
 -0.79125235 -0.54673679  0.73696989  0.92035656  1.10374323  0.675841
 -0.54673679 -1.83044347 -0.11883456  0.37019656 -0.42447901  0.125681
  1.59277435  1.04261434  0.125681    0.49245433 -0.36335012 -1.6470568
  1.2871299  -1.76931458  1.40938768  1.22600101  0.30906767  0.55358322
  0.125681   -0.11883456 -0.36335012  1.47051657 -1.03576791  0.49245433
 -1.76931458  0.61471211  0.92035656  1.65390324 -0.30222123 -0.11883456
  0.37019656  0.675841   -0.3

In [30]:
Normalized_Weight = (Weight-Mean_weight) / Std_dev1_weight
print("Normalized data (Min-Max):", Normalized_Weight)

Normalized data (Min-Max): [-0.30911702 -0.58732233  0.12364681 -0.0618234  -1.39102658 -0.0618234
 -0.43276382  0.15455851 -0.49458723 -0.09273511 -0.77279254 -0.80370424
 -0.15455851 -1.70014359 -0.83461595  0.0309117   0.12364681  0.71096914
  1.20555637  1.02008616  0.12364681  1.32920317 -0.27820532  1.02008616
 -1.20555637 -1.29829147 -0.34002872 -1.36011487  1.63832019  1.42193828
  0.46367553 -1.66923189 -1.26737977  0.77279254  1.45284998  0.80370424
  0.24729361 -0.80370424  1.42193828 -0.77279254  0.43276382  0.0618234
 -1.54558509  0.37094042  0.61823403 -0.92735105  0.49458723  0.15455851
 -1.05099786  1.42193828  0.89643935 -1.60740849  0.12364681 -0.0309117
  0.30911702 -0.52549893 -0.43276382  0.64914574 -1.11282126 -0.55641063
 -1.60740849  1.14373296 -1.60740849 -0.71096914  0.89643935  1.60740849
 -0.30911702 -1.45284998 -0.74188084  0.92735105 -1.70014359  0.34002872
 -0.80370424 -0.95826275 -0.18547021  1.48376168 -0.0618234  -0.49458723
  0.49458723 -1.70014359 -0

##### 16- What are the indices of the tallest people ? 

In [31]:
Tallest_people = np.argmax(Height)
print("The indices of the tallest people is : ", Tallest_people)

The indices of the tallest people is :  100


##### # Sometimes, in logistic regression, for example, we need to find a polynomial fitting function. For that, we need to create a new column for each feature representing a higher degree for that feature.

##### 17- Create two arrays representing the square of both height and weight

In [32]:
Squarted_height = Height**2
Squarted_height

array([30276, 35721, 34225, 38025, 22201, 35721, 21609, 23716, 30276,
       28561, 38025, 25281, 36864, 24025, 36481, 23409, 24649, 19600,
       20736, 29584, 24649, 23409, 28561, 34225, 29584, 22801, 36100,
       34969, 26569, 32041, 23409, 31684, 38025, 25600, 24649, 35721,
       38809, 20736, 29241, 34225, 30625, 22201, 24649, 25921, 33124,
       34225, 35344, 32761, 25921, 19600, 28224, 30976, 26569, 29584,
       38416, 34969, 29584, 31684, 26896, 20449, 36481, 19881, 37249,
       36100, 30625, 32041, 29584, 28224, 26896, 37636, 23409, 31684,
       19881, 32400, 34225, 38809, 27225, 28224, 30976, 32761, 26896,
       27556, 36100, 34596, 28224, 39204, 30625, 21025, 25281, 34225,
       31684, 33489, 37636, 31329, 38809, 28900, 20164, 25600, 38025,
       36100, 39601, 23716, 25921, 39204, 36864, 38025, 27556, 25281,
       32761, 22201, 22500, 21316, 36100, 36864, 31329, 21904, 27225,
       21316, 20736, 30976, 28224, 34969, 34969, 33856, 24964, 24964,
       37636, 21025,

In [35]:
Squarted_weight = Weight ** 2 
Squarted_weight

array([ 9216,  7569, 12100, 10816,  3721, 10816,  8464, 12321,  8100,
       10609,  6561,  6400, 10201,  2601,  6241, 11449, 12100, 16641,
       21025, 19321, 12100, 22201,  9409, 19321,  4489,  4096,  9025,
        3844, 25281, 23104, 14641,  2704,  4225, 17161, 23409, 17424,
       12996,  6400, 23104,  6561, 14400, 11664,  3136, 13924, 15876,
        5776, 14884, 12321,  5184, 23104, 18225,  2916, 12100, 11025,
       13456,  7921,  8464, 16129,  4900,  7744,  2916, 20449,  2916,
        6889, 18225, 24964,  9216,  3481,  6724, 18496,  2601, 13689,
        6400,  5625, 10000, 23716, 10816,  8100, 14884,  2601,  5625,
       19600, 11025, 13924, 15129,  2500, 19881, 13689, 10816, 19600,
       23716,  9216, 12321,  3721, 14161, 24336,  4761, 19321,  4761,
        2500, 24336, 11025, 24025, 21025, 19600, 15876, 25600, 23716,
       11236,  4356,  4900, 24649, 18225,  8100,  9216,  3600,  3249,
       10816, 11664, 24336,  7569, 14884, 19044, 25600, 22201,  9216,
       13225,  6241,

##### 18- Create two arrays representing the quare root of bith height and weight 

In [36]:
Root_height = np.sqrt(Height)
Root_height

array([13.19090596, 13.74772708, 13.60147051, 13.96424004, 12.20655562,
       13.74772708, 12.12435565, 12.40967365, 13.19090596, 13.        ,
       13.96424004, 12.60952021, 13.85640646, 12.4498996 , 13.82027496,
       12.36931688, 12.52996409, 11.83215957, 12.        , 13.11487705,
       12.52996409, 12.36931688, 13.        , 13.60147051, 13.11487705,
       12.28820573, 13.78404875, 13.67479433, 12.76714533, 13.37908816,
       12.36931688, 13.34166406, 13.96424004, 12.64911064, 12.52996409,
       13.74772708, 14.03566885, 12.        , 13.07669683, 13.60147051,
       13.22875656, 12.20655562, 12.52996409, 12.68857754, 13.49073756,
       13.60147051, 13.7113092 , 13.45362405, 12.68857754, 11.83215957,
       12.9614814 , 13.26649916, 12.76714533, 13.11487705, 14.        ,
       13.67479433, 13.11487705, 13.34166406, 12.80624847, 11.95826074,
       13.82027496, 11.87434209, 13.89244399, 13.78404875, 13.22875656,
       13.37908816, 13.11487705, 12.9614814 , 12.80624847, 13.92

In [38]:
Root_weight = np.sqrt(Weight)
Root_weight

array([ 9.79795897,  9.32737905, 10.48808848, 10.19803903,  7.81024968,
       10.19803903,  9.59166305, 10.53565375,  9.48683298, 10.14889157,
        9.        ,  8.94427191, 10.04987562,  7.14142843,  8.88819442,
       10.34408043, 10.48808848, 11.35781669, 12.04159458, 11.78982612,
       10.48808848, 12.20655562,  9.8488578 , 11.78982612,  8.18535277,
        8.        ,  9.74679434,  7.87400787, 12.60952021, 12.32882801,
       11.        ,  7.21110255,  8.06225775, 11.44552314, 12.36931688,
       11.48912529, 10.67707825,  8.94427191, 12.32882801,  9.        ,
       10.95445115, 10.39230485,  7.48331477, 10.86278049, 11.22497216,
        8.71779789, 11.04536102, 10.53565375,  8.48528137, 12.32882801,
       11.61895004,  7.34846923, 10.48808848, 10.24695077, 10.77032961,
        9.43398113,  9.59166305, 11.26942767,  8.36660027,  9.38083152,
        7.34846923, 11.95826074,  7.34846923,  9.11043358, 11.61895004,
       12.56980509,  9.79795897,  7.68114575,  9.05538514, 11.66

##### 19- Extract the last column of the data (the target). What will be its shape


In [39]:
data

array([[174,  96,   4],
       [189,  87,   2],
       [185, 110,   4],
       ...,
       [141, 136,   5],
       [150,  95,   5],
       [173, 131,   5]])

In [41]:
Last_column = data[:,2]
Last_column

array([4, 2, 4, 3, 3, 3, 5, 5, 3, 4, 2, 4, 3, 2, 2, 5, 5, 5, 5, 5, 5, 5,
       4, 5, 2, 3, 3, 1, 5, 5, 5, 1, 1, 5, 5, 4, 3, 4, 5, 2, 4, 5, 2, 5,
       4, 2, 4, 4, 3, 5, 5, 1, 5, 4, 4, 3, 4, 5, 3, 5, 0, 5, 0, 2, 5, 5,
       4, 2, 4, 4, 2, 4, 5, 2, 3, 4, 4, 4, 4, 0, 3, 5, 3, 4, 5, 0, 5, 5,
       5, 5, 5, 3, 3, 2, 4, 5, 4, 5, 1, 0, 4, 5, 5, 4, 4, 4, 5, 5, 4, 3,
       4, 5, 4, 2, 4, 3, 2, 5, 5, 5, 4, 4, 4, 5, 5, 4, 4, 4, 5, 2, 5, 2,
       5, 4, 5, 5, 5, 3, 5, 5, 2, 4, 5, 5, 5, 4, 3, 5, 3, 3, 0, 3, 3, 5,
       5, 4, 3, 5, 3, 4, 2, 2, 3, 5, 4, 2, 4, 5, 3, 2, 4, 5, 5, 4, 4, 4,
       4, 3, 5, 3, 3, 4, 4, 2, 3, 3, 5, 3, 5, 4, 5, 5, 4, 5, 5, 5, 4, 4,
       5, 5, 1, 3, 4, 4, 5, 4, 5, 4, 3, 4, 4, 5, 5, 5, 0, 5, 5, 5, 5, 5,
       2, 5, 4, 5, 0, 5, 3, 4, 5, 5, 4, 2, 3, 3, 4, 3, 5, 5, 2, 5, 3, 2,
       1, 5, 0, 5, 3, 5, 3, 4, 3, 5, 5, 5, 5, 2, 4, 5, 5, 4, 5, 5, 5, 2,
       4, 5, 5, 5, 5, 1, 5, 5, 4, 0, 3, 3, 4, 2, 3, 1, 1, 5, 5, 4, 4, 4,
       4, 5, 2, 5, 4, 3, 3, 4, 5, 5, 2, 4, 3, 4, 5,

##### 20- make it a row vector


In [42]:
Last_column.reshape(500,1)

array([[4],
       [2],
       [4],
       [3],
       [3],
       [3],
       [5],
       [5],
       [3],
       [4],
       [2],
       [4],
       [3],
       [2],
       [2],
       [5],
       [5],
       [5],
       [5],
       [5],
       [5],
       [5],
       [4],
       [5],
       [2],
       [3],
       [3],
       [1],
       [5],
       [5],
       [5],
       [1],
       [1],
       [5],
       [5],
       [4],
       [3],
       [4],
       [5],
       [2],
       [4],
       [5],
       [2],
       [5],
       [4],
       [2],
       [4],
       [4],
       [3],
       [5],
       [5],
       [1],
       [5],
       [4],
       [4],
       [3],
       [4],
       [5],
       [3],
       [5],
       [0],
       [5],
       [0],
       [2],
       [5],
       [5],
       [4],
       [2],
       [4],
       [4],
       [2],
       [4],
       [5],
       [2],
       [3],
       [4],
       [4],
       [4],
       [4],
       [0],
       [3],
       [5],
       [3],
    