In [77]:
import numpy as np
from numpy import loadtxt

1. The data in 'wind.data' has the following format::

        61  1  1 15.04 14.96 13.17  9.29 13.96  9.87 13.67 10.25 10.83 12.58 18.50 15.04
        61  1  2 14.71 16.88 10.83  6.50 12.62  7.67 11.50 10.04  9.79  9.67 17.54 13.83
        61  1  3 18.50 16.88 12.33 10.13 11.17  6.17 11.25  8.04  8.50  7.67 12.75 12.71

   The first three columns are year, month and day.  The
   remaining 12 columns are average windspeeds in knots at 12
   locations in Ireland on that day.

   Use the 'loadtxt' function from numpy to read the data into
   an array.

In [78]:
wind_data = loadtxt('wind.data')
print(wind_data)

[[61.    1.    1.   ... 12.58 18.5  15.04]
 [61.    1.    2.   ...  9.67 17.54 13.83]
 [61.    1.    3.   ...  7.67 12.75 12.71]
 ...
 [78.   12.   29.   ... 16.42 18.88 29.58]
 [78.   12.   30.   ... 12.12 14.67 28.79]
 [78.   12.   31.   ... 11.38 12.08 22.08]]


In [79]:
wind_data.shape

(6574, 15)

In [80]:
dates = wind_data[:,:3] # Year / Month / Day 
dates

array([[61.,  1.,  1.],
       [61.,  1.,  2.],
       [61.,  1.,  3.],
       ...,
       [78., 12., 29.],
       [78., 12., 30.],
       [78., 12., 31.]])

In [81]:
data = wind_data[:, 3:]
data

array([[15.04, 14.96, 13.17, ..., 12.58, 18.5 , 15.04],
       [14.71, 16.88, 10.83, ...,  9.67, 17.54, 13.83],
       [18.5 , 16.88, 12.33, ...,  7.67, 12.75, 12.71],
       ...,
       [14.  , 10.29, 14.42, ..., 16.42, 18.88, 29.58],
       [18.5 , 14.04, 21.29, ..., 12.12, 14.67, 28.79],
       [20.33, 17.41, 27.29, ..., 11.38, 12.08, 22.08]])

2. Calculate the min, max and mean windspeeds and standard deviation of the
   windspeeds over all the locations and all the times (a single set of numbers
   for the entire dataset).

In [82]:
print('2. Statistics over all values')

Min_windspeed = np.min(data)
print("\nThe min windspeeds is : ",Min_windspeed)

Max_windspeed = np.max(data)
print("\nThe max windspeeds is : ",Max_windspeed)

Mean_windspeed = np.mean(data).round(2)
print("\nThe min windspeeds is : ",Mean_windspeed)

Std_windspeed = np.std(data).round(2)
print("\nThe standar deviation of the windspeed is:", Std_windspeed)



2. Statistics over all values

The min windspeeds is :  0.0

The max windspeeds is :  42.54

The min windspeeds is :  10.23

The standar deviation of the windspeed is: 5.6


3. Calculate the min, max and mean windspeeds and standard deviations of the
   windspeeds at each location over all the days (a different set of numbers
   for each location)

In [83]:
print('3. Statistics over all days at each location')

Min_windspeed_0 = np.min(data, axis= 0)
print("\nThe min ",Min_windspeed_0)

Max_windspeed_0 = np.max(data, axis= 0)
print("\nThe max  ",Max_windspeed_0)

Mean_windspeed_0 = np.mean(data, axis= 0)
print("\nThe min ",Mean_windspeed_0)

Std_windspeed_0 = np.std(data, axis= 0)
print("\nThe standar deviation ", Std_windspeed_0)

3. Statistics over all days at each location

The min  [0.67 0.21 1.5  0.   0.13 0.   0.   0.   0.   0.04 0.13 0.67]

The max   [35.8  33.37 33.84 28.46 37.54 26.16 30.37 31.08 25.88 28.21 42.38 42.54]

The min  [12.36371463 10.64644813 11.66010344  6.30627472 10.45688013  7.09225434
  9.7968345   8.49442044  8.49581838  8.70726803 13.121007   15.59946152]

The standar deviation  [5.61918301 5.26820081 5.00738377 3.60513309 4.93536333 3.96838126
 4.97689374 4.49865783 4.16746101 4.50327222 5.83459319 6.69734719]


4. Calculate the min, max and mean windspeed and standard deviations of the
   windspeeds across all the locations at each day (a different set of numbers
   for each day)

In [84]:
print('4. Statistics over all locations for each day')


Min_windspeed_1 = np.min(data, axis= 1)
print("\nThe min  : ",Min_windspeed_1)

Max_windspeed_1 = np.max(data, axis= 1)
print("\nThe max : ",Max_windspeed_1)

Mean_windspeed_1 = np.mean(data, axis= 1)
print("\nThe min  : ",Mean_windspeed_1)

Std_windspeed_1 = np.std(data, axis= 1)
print("\nThe standar deviation ", Std_windspeed_1)

4. Statistics over all locations for each day

The min  :  [9.29 6.5  6.17 ... 8.71 9.13 9.59]

The max :  [18.5  17.54 18.5  ... 29.58 28.79 27.29]

The min  :  [13.09666667 11.79833333 11.34166667 ... 14.89       15.3675
 15.4025    ]

The standar deviation  [2.5773188  3.28972854 3.50543348 ... 5.51175108 5.30456427 5.45971172]


5. Find the location which has the greatest windspeed on each day (an integer
   column number for each day).

In [85]:
Arg_max_windspeed_1 = np.argmax(data, axis= 1)
print("\nThe Location which has the greattest windspeed is  : ",Arg_max_windspeed_1)


The Location which has the greattest windspeed is  :  [10 10  0 ... 11 11  2]


6. Find the year, month and day on which the greatest windspeed was recorded.


In [92]:
daily_max = data.max(axis=1)
max_row = daily_max.argmax()


print("\nMaximum values per row:", daily_max)  
print("\nRow with the highest maximum value:", max_row)

print('\n6. The year, month and day on which the greatest windspeed was recorded')
print('\nYear:', int(wind_data[max_row, 0]))
print('\nMonth:', int(wind_data[max_row, 1]))
print('\nDay:', int(wind_data[max_row, 2]))







Maximum values per row: [18.5  17.54 18.5  ... 29.58 28.79 27.29]

Row with the highest maximum value: 2161

6. The year, month and day on which the greatest windspeed was recorded

Year: 66

Month: 12

Day: 2


7. Find the average windspeed in January for each location.

In [87]:
Junary_indices = wind_data[:,1] == 1
Junary_data = data[Junary_indices]
Mean_junary = np.mean(Junary_data, axis=0)

In [88]:
print('7. Statistics for January')
print('  mean:', Mean_junary) 

7. Statistics for January
  mean: [14.86955197 12.92166667 13.29962366  7.19949821 11.67571685  8.05483871
 11.81935484  9.5094086   9.54320789 10.05356631 14.55051971 18.02876344]
